CREATE TABLE EVENT (
    EVENT_ID          NUMBER          PRIMARY KEY,
    BOOK_ID           VARCHAR2(20)    NULL,
    TICKET_TYPE       VARCHAR2(20)    NOT NULL,
    EVENT_NAME        VARCHAR2(200)   NOT NULL,
    EVENT_DECRIPTION  VARCHAR2(4000)  NOT NULL,
    EVENT_PRICE       NUMBER          NOT NULL,
    EVENT_IMAGE       VARCHAR2(1000)  NULL,
    LOCAL_CODE        VARCHAR2(20)    NOT NULL,
    ADDRESS           VARCHAR2(2000)  NOT NULL
);

-- [제약조건] 티켓 타입
ALTER TABLE EVENT ADD CONSTRAINT CHK_TICKET_TYPE 
CHECK (TICKET_TYPE IN ('SEAT_TYPE', 'PERSON_TYPE'));

-- [제약조건] 지역코드 
ALTER TABLE EVENT ADD CONSTRAINT CHK_LOCAL_CODE 
CHECK (LOCAL_CODE IN ('SEOUL', 'GYEONGGI_INCHEON', 'JEOLLA', 'GYEONGSANG', 'GANGWON', 'CHUNGCHEONG', 'JEJU'));

-- EVENT 테이블의 BOOK_ID를 BOOK 테이블의 BOOK_ID와 연결
ALTER TABLE EVENT ADD CONSTRAINT FK_EVENT_BOOK FOREIGN KEY (BOOK_ID)
REFERENCES BOOK (BOOK_ID);