-- USERS 테이블
CREATE TABLE USERS(
    USER_ID       VARCHAR2(50)    PRIMARY KEY,
    USER_PW       VARCHAR2(100)   NOT NULL,
    USER_NAME     VARCHAR2(50)    NOT NULL,
    EMAIL         VARCHAR2(100)   NOT NULL,
    PHONE         VARCHAR2(20)    NOT NULL,
    BIRTH         DATE            NOT NULL,
    ISACTIVE      CHAR(1)         NOT NULL,
    USER_REGDATE  DATE            NOT NULL,
    REFRESH_TOKEN VARCHAR2(255)   NULL
);

-- [고유 키] EMAIL
ALTER TABLE USERS ADD CONSTRAINT UQ_USERS_EMAIL UNIQUE (EMAIL);

-- [고유 키] PHONE
ALTER TABLE USERS ADD CONSTRAINT UQ_USERS_PHONE UNIQUE (PHONE);

-- [제약조건] ISACTIVE
ALTER TABLE USERS ADD CONSTRAINT CHK_USERS_ISACTIVE 
CHECK (ISACTIVE IN ('Y', 'N'));